from src.enums import IssueProgressEnum as IssueProgressEnum
from starlette.datastructures import FormData as FormData
from starlette.requests import Request as Request
from starlette.responses import JSONResponse

async def details_request(request: Request) -> JSONResponse: ...
async def submit_issue(request: Request) -> JSONResponse: ...
async def delete_issues(request: Request) -> JSONResponse: ...
async def fetch_issues(request: Request) -> JSONResponse: ...
async def edit_issue(request: Request) -> None: ...
