"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class HealthStatusRequest(google.protobuf.message.Message):
    """import "google/protobuf/timestamp.proto";

    Health Check
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___HealthStatusRequest = HealthStatusRequest

@typing.final
class HealthStatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    version: builtins.str
    status: builtins.str
    def __init__(
        self,
        *,
        version: builtins.str = ...,
        status: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status", b"status", "version", b"version"]) -> None: ...

global___HealthStatusResponse = HealthStatusResponse

@typing.final
class GSEDetailsRequest(google.protobuf.message.Message):
    """GSE Details"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GSE_ID_FIELD_NUMBER: builtins.int
    gse_id: builtins.str
    def __init__(
        self,
        *,
        gse_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["gse_id", b"gse_id"]) -> None: ...

global___GSEDetailsRequest = GSEDetailsRequest

@typing.final
class GSEDetailsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GSE_ID_FIELD_NUMBER: builtins.int
    OLD_GSE_ID_FIELD_NUMBER: builtins.int
    GSE_TYPE_FIELD_NUMBER: builtins.int
    MODEL_FIELD_NUMBER: builtins.int
    MANUFACTURER_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    ISSUE_COUNT_FIELD_NUMBER: builtins.int
    TYPE_OF_FUEL_FIELD_NUMBER: builtins.int
    IN_USE_FIELD_NUMBER: builtins.int
    MOST_RECENT_ISSUE_FIELD_NUMBER: builtins.int
    LIFT_INSPECTION_EXPIRES_FIELD_NUMBER: builtins.int
    LATEST_SERVICE_CHASSI_FIELD_NUMBER: builtins.int
    LATEST_SERVICE_UNIT_FIELD_NUMBER: builtins.int
    CAPACITY_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    gse_id: builtins.str
    old_gse_id: builtins.str
    gse_type: builtins.str
    model: builtins.str
    manufacturer: builtins.str
    location: builtins.str
    status: builtins.str
    issue_count: builtins.int
    type_of_fuel: builtins.str
    in_use: builtins.bool
    lift_inspection_expires: builtins.str
    latest_service_chassi: builtins.str
    latest_service_unit: builtins.str
    capacity: builtins.float
    details: builtins.str
    error: builtins.str
    @property
    def most_recent_issue(self) -> global___MostRecentIssueResponse: ...
    def __init__(
        self,
        *,
        gse_id: builtins.str = ...,
        old_gse_id: builtins.str = ...,
        gse_type: builtins.str = ...,
        model: builtins.str = ...,
        manufacturer: builtins.str = ...,
        location: builtins.str = ...,
        status: builtins.str = ...,
        issue_count: builtins.int = ...,
        type_of_fuel: builtins.str = ...,
        in_use: builtins.bool = ...,
        most_recent_issue: global___MostRecentIssueResponse | None = ...,
        lift_inspection_expires: builtins.str = ...,
        latest_service_chassi: builtins.str = ...,
        latest_service_unit: builtins.str = ...,
        capacity: builtins.float | None = ...,
        details: builtins.str | None = ...,
        error: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_capacity", b"_capacity", "_details", b"_details", "_error", b"_error", "capacity", b"capacity", "details", b"details", "error", b"error", "most_recent_issue", b"most_recent_issue"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_capacity", b"_capacity", "_details", b"_details", "_error", b"_error", "capacity", b"capacity", "details", b"details", "error", b"error", "gse_id", b"gse_id", "gse_type", b"gse_type", "in_use", b"in_use", "issue_count", b"issue_count", "latest_service_chassi", b"latest_service_chassi", "latest_service_unit", b"latest_service_unit", "lift_inspection_expires", b"lift_inspection_expires", "location", b"location", "manufacturer", b"manufacturer", "model", b"model", "most_recent_issue", b"most_recent_issue", "old_gse_id", b"old_gse_id", "status", b"status", "type_of_fuel", b"type_of_fuel"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_capacity", b"_capacity"]) -> typing.Literal["capacity"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_details", b"_details"]) -> typing.Literal["details"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_error", b"_error"]) -> typing.Literal["error"] | None: ...

global___GSEDetailsResponse = GSEDetailsResponse

@typing.final
class ListGSEReponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GSE_ID_FIELD_NUMBER: builtins.int
    @property
    def gse_id(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        gse_id: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["gse_id", b"gse_id"]) -> None: ...

global___ListGSEReponse = ListGSEReponse

@typing.final
class MostRecentIssueResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    GSE_ID_FIELD_NUMBER: builtins.int
    ISSUE_DESCRIPTION_FIELD_NUMBER: builtins.int
    REPORTED_AT_FIELD_NUMBER: builtins.int
    ATTACHMENTS_FIELD_NUMBER: builtins.int
    id: builtins.str
    gse_id: builtins.str
    issue_description: builtins.str
    reported_at: builtins.str
    attachments: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        gse_id: builtins.str = ...,
        issue_description: builtins.str = ...,
        reported_at: builtins.str = ...,
        attachments: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["attachments", b"attachments", "gse_id", b"gse_id", "id", b"id", "issue_description", b"issue_description", "reported_at", b"reported_at"]) -> None: ...

global___MostRecentIssueResponse = MostRecentIssueResponse

@typing.final
class SubmitIssueRequest(google.protobuf.message.Message):
    """Submit Issue"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GSE_ID_FIELD_NUMBER: builtins.int
    WORKER_ID_FIELD_NUMBER: builtins.int
    ISSUE_DESCRIPTION_FIELD_NUMBER: builtins.int
    IS_OPERABLE_FIELD_NUMBER: builtins.int
    ATTACHMENTS_FIELD_NUMBER: builtins.int
    GATE_TYPE_FIELD_NUMBER: builtins.int
    GATE_NAME_FIELD_NUMBER: builtins.int
    gse_id: builtins.str
    worker_id: builtins.str
    issue_description: builtins.str
    is_operable: builtins.str
    gate_type: builtins.str
    gate_name: builtins.str
    @property
    def attachments(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        gse_id: builtins.str = ...,
        worker_id: builtins.str = ...,
        issue_description: builtins.str = ...,
        is_operable: builtins.str = ...,
        attachments: collections.abc.Iterable[builtins.bytes] | None = ...,
        gate_type: builtins.str | None = ...,
        gate_name: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_gate_name", b"_gate_name", "_gate_type", b"_gate_type", "gate_name", b"gate_name", "gate_type", b"gate_type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_gate_name", b"_gate_name", "_gate_type", b"_gate_type", "attachments", b"attachments", "gate_name", b"gate_name", "gate_type", b"gate_type", "gse_id", b"gse_id", "is_operable", b"is_operable", "issue_description", b"issue_description", "worker_id", b"worker_id"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_gate_name", b"_gate_name"]) -> typing.Literal["gate_name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_gate_type", b"_gate_type"]) -> typing.Literal["gate_type"] | None: ...

global___SubmitIssueRequest = SubmitIssueRequest

@typing.final
class SubmitIssueResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___SubmitIssueResponse = SubmitIssueResponse

@typing.final
class FetchIssuesRequest(google.protobuf.message.Message):
    """Fetch Issues"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAGE_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    page: builtins.int
    page_size: builtins.int
    def __init__(
        self,
        *,
        page: builtins.int = ...,
        page_size: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["page", b"page", "page_size", b"page_size"]) -> None: ...

global___FetchIssuesRequest = FetchIssuesRequest

@typing.final
class FetchIssuesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    PAGE_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    TOTAL_FIELD_NUMBER: builtins.int
    page: builtins.int
    page_size: builtins.int
    total: builtins.int
    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Issue]: ...
    def __init__(
        self,
        *,
        data: collections.abc.Iterable[global___Issue] | None = ...,
        page: builtins.int = ...,
        page_size: builtins.int = ...,
        total: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "page", b"page", "page_size", b"page_size", "total", b"total"]) -> None: ...

global___FetchIssuesResponse = FetchIssuesResponse

@typing.final
class Issue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    GSE_ID_FIELD_NUMBER: builtins.int
    ISSUE_DESCRIPTION_FIELD_NUMBER: builtins.int
    ESTIMATED_TIME_FIELD_NUMBER: builtins.int
    REPORTED_AT_FIELD_NUMBER: builtins.int
    REPORTED_BY_FIELD_NUMBER: builtins.int
    PROGRESS_FIELD_NUMBER: builtins.int
    ATTACHMENTS_FIELD_NUMBER: builtins.int
    id: builtins.str
    gse_id: builtins.str
    issue_description: builtins.str
    estimated_time: builtins.str
    reported_at: builtins.str
    reported_by: builtins.str
    progress: builtins.str
    @property
    def attachments(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Attachment]: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        gse_id: builtins.str = ...,
        issue_description: builtins.str = ...,
        estimated_time: builtins.str = ...,
        reported_at: builtins.str = ...,
        reported_by: builtins.str = ...,
        progress: builtins.str = ...,
        attachments: collections.abc.Iterable[global___Attachment] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["attachments", b"attachments", "estimated_time", b"estimated_time", "gse_id", b"gse_id", "id", b"id", "issue_description", b"issue_description", "progress", b"progress", "reported_at", b"reported_at", "reported_by", b"reported_by"]) -> None: ...

global___Issue = Issue

@typing.final
class Attachment(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    FILE_TYPE_FIELD_NUMBER: builtins.int
    UPLOADED_AT_FIELD_NUMBER: builtins.int
    id: builtins.str
    file_type: builtins.str
    uploaded_at: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        file_type: builtins.str = ...,
        uploaded_at: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["file_type", b"file_type", "id", b"id", "uploaded_at", b"uploaded_at"]) -> None: ...

global___Attachment = Attachment

@typing.final
class SetLanguageRequest(google.protobuf.message.Message):
    """Set Language"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LANGUAGE_FIELD_NUMBER: builtins.int
    language: builtins.str
    def __init__(
        self,
        *,
        language: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["language", b"language"]) -> None: ...

global___SetLanguageRequest = SetLanguageRequest

@typing.final
class SetLanguageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    token: builtins.str
    def __init__(
        self,
        *,
        token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["token", b"token"]) -> None: ...

global___SetLanguageResponse = SetLanguageResponse

@typing.final
class LoginRequest(google.protobuf.message.Message):
    """Login"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMAIL_FIELD_NUMBER: builtins.int
    email: builtins.str
    def __init__(
        self,
        *,
        email: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["email", b"email"]) -> None: ...

global___LoginRequest = LoginRequest

@typing.final
class LoginResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    message: builtins.str
    def __init__(
        self,
        *,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message"]) -> None: ...

global___LoginResponse = LoginResponse

@typing.final
class DeleteIssuesRequest(google.protobuf.message.Message):
    """Delete Issues"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IDS_FIELD_NUMBER: builtins.int
    @property
    def ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        ids: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ids", b"ids"]) -> None: ...

global___DeleteIssuesRequest = DeleteIssuesRequest

@typing.final
class DeleteIssuesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___DeleteIssuesResponse = DeleteIssuesResponse

@typing.final
class LogoutRequest(google.protobuf.message.Message):
    """Logout"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___LogoutRequest = LogoutRequest

@typing.final
class LogoutResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    message: builtins.str
    def __init__(
        self,
        *,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message"]) -> None: ...

global___LogoutResponse = LogoutResponse

@typing.final
class FetchGatesRequest(google.protobuf.message.Message):
    """Fetch Gates"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ICAO_CODE_FIELD_NUMBER: builtins.int
    icao_code: builtins.str
    def __init__(
        self,
        *,
        icao_code: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["icao_code", b"icao_code"]) -> None: ...

global___FetchGatesRequest = FetchGatesRequest

@typing.final
class FetchGatesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GATES_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    error: builtins.str
    @property
    def gates(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Gate]: ...
    def __init__(
        self,
        *,
        gates: collections.abc.Iterable[global___Gate] | None = ...,
        error: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "gates", b"gates"]) -> None: ...

global___FetchGatesResponse = FetchGatesResponse

@typing.final
class Gate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    id: builtins.str
    name: builtins.str
    type: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        name: builtins.str = ...,
        type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "name", b"name", "type", b"type"]) -> None: ...

global___Gate = Gate

@typing.final
class IssueComment(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISSUE_ID_FIELD_NUMBER: builtins.int
    COMMENT_FIELD_NUMBER: builtins.int
    COMMENT_BY_FIELD_NUMBER: builtins.int
    issue_id: builtins.str
    comment: builtins.str
    comment_by: builtins.str
    def __init__(
        self,
        *,
        issue_id: builtins.str = ...,
        comment: builtins.str = ...,
        comment_by: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["comment", b"comment", "comment_by", b"comment_by", "issue_id", b"issue_id"]) -> None: ...

global___IssueComment = IssueComment

@typing.final
class IssueCommentResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    id: builtins.str
    error: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        error: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "id", b"id"]) -> None: ...

global___IssueCommentResponse = IssueCommentResponse

@typing.final
class UploadFieldImage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IMAGE_FIELD_NUMBER: builtins.int
    GSE_ID_FIELD_NUMBER: builtins.int
    image: builtins.bytes
    gse_id: builtins.str
    def __init__(
        self,
        *,
        image: builtins.bytes = ...,
        gse_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["gse_id", b"gse_id", "image", b"image"]) -> None: ...

global___UploadFieldImage = UploadFieldImage

@typing.final
class UploadFieldImageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    success: builtins.str
    error: builtins.str
    def __init__(
        self,
        *,
        success: builtins.str = ...,
        error: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "success", b"success"]) -> None: ...

global___UploadFieldImageResponse = UploadFieldImageResponse

@typing.final
class FieldImageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GSE_ID_FIELD_NUMBER: builtins.int
    gse_id: builtins.str
    def __init__(
        self,
        *,
        gse_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["gse_id", b"gse_id"]) -> None: ...

global___FieldImageRequest = FieldImageRequest

@typing.final
class FieldImageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IMAGE_FIELD_NUMBER: builtins.int
    DELETE_SUCCESS_FIELD_NUMBER: builtins.int
    image: builtins.bytes
    delete_success: builtins.bool
    def __init__(
        self,
        *,
        image: builtins.bytes = ...,
        delete_success: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["delete_success", b"delete_success", "image", b"image"]) -> None: ...

global___FieldImageResponse = FieldImageResponse
