from tortoise import fields
from tortoise.models import Model


class GeneratedModel(Model):
    id = fields.UUIDField(pk=True)
    gse_id = fields.CharField(max_length=255)
    old_gse_id = fields.CharField(max_length=255)
    gse_type = fields.CharField(max_length=255)
    model = fields.CharField(max_length=255)
    manufacturer = fields.CharField(max_length=255)
    location = fields.CharField(max_length=255)
    lift_inspection_expire = fields.DatetimeField(max_length=255)
    latest_service_chassi = fields.DatetimeField()
    latest_service_unit = fields.DatetimeField()
    chassi_nrvehicle = fields.IntField()
    chassi_nrunit = fields.IntField()
    manufacutring_year_chassi = fields.IntField()
    manufacutring_year_unit = fields.IntField()
    hour_meter_chassi = fields.IntField()
    hour_meter_unit = fields.IntField()
    km_chassi = fields.IntField()
    local_vehicle_permit = fields.CharField(max_length=255)
    vehicle_permition_nr = fields.CharField(max_length=255)
    vehicle_permit_valid_until = fields.CharField(max_length=255)
    in_use = fields.BooleanField()
    net_weight_kg = fields.IntField(max_length=255)
    total_weight_kg = fields.IntField(max_length=255)
    status = fields.CharField(max_length=255)
    type_of_fuel = fields.CharField(max_length=255)
    emission_standard = fields.CharField(max_length=255)
    regnrif_applicable = fields.CharField(max_length=255)
    heating = fields.CharField(max_length=255)
    deice_type = fields.CharField(max_length=255)
    hot_type4 = fields.BooleanField()
    glycol = fields.BooleanField()
    capacity = fields.CharField(max_length=255)
    actype = fields.CharField(max_length=255)
    singel_double_max_ppm = fields.CharField(max_length=255)
    power = fields.CharField(max_length=255)
    cabin = fields.BooleanField()
    gen2 = fields.BooleanField()
    length_m = fields.IntField(max_length=255)
    height_min_max_mm = fields.CharField(max_length=255)
    self_propp = fields.BooleanField()
    owned_by_company = fields.CharField(max_length=255)
    owned_by_company2 = fields.CharField(max_length=255)
    type_of_lease = fields.CharField(max_length=255)
    term_of_termination = fields.CharField(max_length=255)
    purchase_date = fields.DatetimeField()
    agreement_expire_date = fields.DatetimeField()
    risk_assessment = fields.BooleanField()
    training_documentation_available = fields.BooleanField()
    item_type = fields.CharField(max_length=255)
    path = fields.CharField(max_length=255)