from datetime import datetime as datetime
from tortoise.fields import Field as Field
from tortoise.models import Model
from uuid import UUID as UUID

class GroundSupportEquiptment(Model):
    id: Field[UUID]
    gse_id: Field[str]
    old_gse_id: Field[str]
    gse_type: Field[str]
    model: Field[str]
    manufacturer: Field[str]
    location: Field[str]
    lift_inspection_expires: Field[datetime]
    latest_service_chassi: Field[datetime]
    latest_service_unit: Field[datetime]
    chassi_nr_vehicle: Field[str]
    chassi_nr_unit: Field[int]
    manufacturing_year_chassi: Field[int]
    manufacturing_year_unit: Field[int]
    hour_meter_chassi: Field[str]
    hour_meter_unit: Field[int]
    km_chassi: Field[int]
    local_vehicle_permit: Field[str]
    vehicle_permit_nr: Field[str]
    vehicle_permit_valid_until: Field[str]
    in_use: Field[bool]
    net_weight_kg: Field[int]
    total_weight_kg: Field[int]
    status: Field[str]
    type_of_fuel: Field[str]
    emission_standard: Field[str]
    reg_nr_if_applicable: Field[str]
    heating: Field[str]
    deice_type: Field[str]
    hot_type4: Field[bool]
    glycol: Field[bool]
    capacity: Field[str]
    ac_type: Field[str]
    single_double_max_ppm: Field[str]
    power: Field[str]
    cabin: Field[bool]
    gen2: Field[bool]
    length_m: Field[int]
    height_min_max_mm: Field[str]
    self_propelled: Field[bool]
    owned_by_company: Field[str]
    owned_by_company2: Field[str]
    type_of_lease: Field[str]
    term_of_termination: Field[str]
    purchase_date: Field[datetime]
    agreement_expire_date: Field[datetime]
    risk_assessment: Field[bool]
    training_documentation_available: Field[bool]
    item_type: Field[str]
    path: Field[str]
    field_image: Field[bytes]
    def generate_qr_code(self) -> None: ...
